### PR TITLE
Updated homepage to delete checklist

### PR DESCRIPTION
**Pull request by dsacco15**
# Updated homepage title to delete "checklist"

### CODE REVIEW

**Comment by redhat-training-curriculum** [comment]
HTML Built Successfully, preview [here](http://jenkins.prod.nextcle.com/job/RHT/job/curriculum-onboarding/job/PR-29/1/Onboarding_20Documentation_20HTML)

**Comment by PatSharp99** [comment]
Looks good. Thank you.

**Comment by dsacco15** [comment]
@PatSharp99 , let me know if this allows you to approve.

**Review by nmuller66 — APPROVED** [review]
Looks good

**Pull request merged**
