### PR TITLE
Review changes and additions to the onboarding structure.

### PR DESCRIPTION
**Pull request by dsacco15**
# Added structure and some content

## First stab at adding content. I was learning asciidoc as I went so it's a bit rough and the order within course-dev is wrong but it's a start. 

Please take a look and provide feedback or first impressions. Feel free to update or modify anything as well. Use the review link to HTML below to see it in context.

Happy Holidays and I am out (for now)!
D

### CODE REVIEW

**Comment by redhat-training-curriculum** [comment]
HTML Built Successfully, preview [here](http://jenkins.prod.nextcle.com/job/RHT/job/curriculum-onboarding/job/PR-6/1/Onboarding_20Documentation_20HTML)

**Comment by dsacco15** [comment]
With Richard's help, I corrected the contents for course-dev.

**Comment by daobrien** [comment]
I strongly recommend that you spend some time just planning the site structure, without committing anything. You can do this in a plain text file using bulleted lists. Basically all you need to do is create a TOC with minimal content. When you get consensus on that you can start filling in the blanks. Treat it much like we do iterative development: Build a TOC; get ack; rebuild and push; rinse and repeat. Remember that you can review the entire site locally; you don't have to push everything and have Jenkins rebuild it.

I would also do much smaller updates. This PR contains almost 20 commits, many of which are just tests.

**Comment by sffrench** [comment]
Great work so far Dave, wow, well done on the upskilling, you are doing an awesome job! Can't wait to see more.

**Comment by daobrien** [comment]
Spoke to Dave and helped him get his process sorted, etc. Closing this PR as a "won't do"

**Pull request closed without merging**
