### PR TITLE
First cut of Content Services references for writers and editors.

### LINKED ISSUE #3: Start adding references
https://source.redhat.com/groups/public/gls-content-services/gls_content_services_wiki/index_article_references

Go through the links here and add to suitable locations.

### PR DESCRIPTION
**Pull request by daobrien**
# Initial Cut of Writing References

## Description

Adds *References* to the main menu and includes links to main dictionaries and style guides.

Fixes #3 

## Type of change

Please delete options that are not relevant.

- [ ] New feature (non-breaking change which adds functionality)

### CODE REVIEW

**Comment by redhat-training-curriculum** [comment]
HTML Built Successfully, preview [here](http://jenkins.prod.nextcle.com/job/RHT/job/curriculum-onboarding/job/PR-4/1/Onboarding_20Documentation_20HTML)

**Comment by alexpdp7** [comment]
Note that you are linking to:

https://github.com/RedHatTraining/content-services-docs/tree/master/publishing-content/ibm-word-usage-2020.pdf

, which in turn is a symlink to:

https://github.com/RedHatTraining/content-services-docs/blob/master/publishing-content/ibm-wug.adoc

. I noticed this file seems to be truncated (the last entry is "direct access storage device"). There is another file with the same name at the root of the repo which seems to be completed. Created https://github.com/RedHatTraining/content-services-docs/pull/191 to fix.

**Comment by daobrien** [comment]
> Note that you are linking to:
> 
> https://github.com/RedHatTraining/content-services-docs/tree/master/publishing-content/ibm-word-usage-2020.pdf
> 
> , which in turn is a symlink to:
> 
> https://github.com/RedHatTraining/content-services-docs/blob/master/publishing-content/ibm-wug.adoc
> 
> . I noticed this file seems to be truncated (the last entry is "direct access storage device"). There is another file with the same name at the root of the repo which seems to be completed. Created [RedHatTraining/content-services-docs#191](https://github.com/RedHatTraining/content-services-docs/pull/191) to fix.

Instead of a separate issue can you make this a fix request for the initial PR? thanks

**Comment by alexpdp7** [comment]
> Instead of a separate issue can you make this a fix request for the initial PR? thanks

This PR is linking to the WUG in the "correct directory", it's just that it's truncated. My PR would fix the WUG you link to with the full version (and remove a copy in an odd location).

So both PRs can be merged independently and they don't need any further changes.

**Review by dsacco15 — APPROVED** [review]
These look good to me. When you push exemplars, unless they are cherry-picked, will also include ID-specific examples. Is this intended?

**Comment by PatSharp99** [comment]
Reference list looks good. Thank you!

**Comment by daobrien** [comment]
> These look good to me. When you push exemplars, unless they are cherry-picked, will also include ID-specific examples. Is this intended?

Do you mean am I pushing all the exemplars or just the tech writing ones? If so, I'm pushing the whole page. No point picking and choosing bits and pieces.

**Pull request merged**
